### ISSUE TITLE
nsq消息队列

### ISSUE THREAD

**Issue by jamesBan** [jamesBan/jamesBan.github.io#5]
## install with docker

`docker-compose.yaml`

```yaml
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd-1:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqd-2:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"
```

```
docker-compose up -d
docker-compsoer ps

#nsq admin
curl http://127.0.0.1:32780

#test
curl -d 'hello world 2' 'http://127.0.0.1:32783/pub?topic=test'
curl -d 'hello world 3' 'http://127.0.0.1:32785/pub?topic=test'
```

##  topic/ channel

![](http://ww1.sinaimg.cn/large/006tNc79ly1g5ax4nvqf0g30bo07tjry.gif)

topic 下可以有多个channel

每个channel下有一个或多个消费者

- 多个Consumer消费同一个Topic和同一个Channel：将会轮训
- 多个Consumer消费同一个Topic和不同的Channel：将会将同一个数据同时到不同的Channel中

## consumer

```go
package main

import "github.com/nsqio/go-nsq"

func main() {
	//consumer1
	consumer1, err := nsq.NewConsumer("test", "test_channel", nsq.NewConfig())
	if err != nil {
		panic(err)
	}
	consumer1.AddConcurrentHandlers(nsq.HandlerFunc(func(msg *nsq.Message) error {
		fmt.Println("Consumer1:", string(msg.Body))
		return nil
	}), 5)

	err = consumer.ConnectToNSQDs([]string{nsqd1, nsqd2})
	if err != nil {
		panic(err)
	}

	//consumer2
	consumer2, err := nsq.NewConsumer("test", "test_channel-2", nsq.NewConfig())
	if err != nil {
		panic(err)
	}

	consumer2.AddHandler(nsq.HandlerFunc(func(msg *nsq.Message) error {
		fmt.Println("Consumer2:", string(msg.Body))
		return nil
	}))
	err = consumer2.ConnectToNSQDs([]string{nsqd1, nsqd2})
	if err != nil {
		panic(err)
	}

	//daemon until stop
	shutdown := make(chan os.Signal, 2)
	signal.Notify(shutdown, syscall.SIGINT)
	for {
		select {
		case <-consumer.StopChan:
			return
		case <-shutdown:
			consumer.Stop()
		}
	}
}


```

## producer

```go
package main

import "github.com/nsqio/go-nsq"

func main() {
	producer, err := nsq.NewProducer(nsqd_address, nsq.NewConfig())
	if err != nil {
		panic(err)
	}

	err = producer.Publish("test", []byte("this is test"))
	if err != nil {
		panic(err)
	}

	err = producer.DeferredPublish("test", time.Second*10, []byte("deferred message"))
	if err != nil {
		panic(err)
	}
}

```
### 问题

nsq目前不支持顺序消费，解决办法有两个

1、需要循序消费的数据放置在单独的channel，对应的消费者设置单个worker

2、使用有赞二次开发的[nsq](https://github.com/youzan/nsq)
